name: Convert

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 5'  # 每周五 UTC 22:00，即每周六中国时间 6:00

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:    
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout ForestL18/meta-rules-converter
        uses: actions/checkout@v4
        with:
          repository: ForestL18/meta-rules-converter
          path: convert
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Conversion
        run: |
          wget -O awavenue-ads.yaml https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
          ls -la
          cat awavenue-ads.yaml
          cd convert
          go run ./ textfile -i ../ -o ../ -b domain
          realpath ../custom_reject.mrs 
          ls ${{ github.workspace }} -l

      # - name: Upload MRS files to GitHub Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: '${{ github.workspace }}/*.mrs'  # 替换为实际的文件路径
      #     tag: 'mrs'  # 固定标签
      #     replacesArtifacts: true
      #     allowUpdates: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push only .mrs files to mrs branch
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git checkout -B mrs  # 切换到 mrs 分支
          # 移动 .mrs 文件到单独目录，避免误删
          mkdir -p mrs_files
          mv *.mrs mrs_files/
          git rm -rf .         # 删除所有文件
          mv mrs_files/* .     # 恢复 .mrs 文件到根目录
          rmdir mrs_files
          git add ./*.mrs      # 添加 .mrs 文件
          git commit -m "Keep only .mrs files in mrs branch"
          git push origin mrs --force  # 强制推送到 mrs 分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}